//Element descriptions.
#define PT_ELEM_116_DESC L"A failed shared velocity test."
#define PT_ELEM_146_DESC L"Brian 6 S6/B246/3"
#define PT_ELEM_ACEL_DESC L"Accelerator, speeds up nearby elements."
#define PT_ELEM_ACID_DESC L"Dissolves almost everything."
#define PT_ELEM_AMTR_DESC L"Anti-Matter, destroys a majority of particles."
#define PT_ELEM_ANAR_DESC L"Anti-air. Very light dust, which behaves opposite gravity."
#define PT_ELEM_ARAY_DESC L"Ray Emitter. Rays create points when they collide."
#define PT_ELEM_BANG_DESC L"TNT, explodes all at once."
#define PT_ELEM_BCLN_DESC L"Breakable Clone."
#define PT_ELEM_BCOL_DESC L"Broken Coal. Heavy particles, burns slowly."
#define PT_ELEM_BGLA_DESC L"Broken Glass, heavy particles formed when glass breaks under pressure. Meltable. Bagels."
#define PT_ELEM_BHOL_DESC L"Vacuum, sucks in other particles and heats up."
#define PT_ELEM_BIZR_DESC L"Bizarre... contradicts the normal state changes. Paints other elements with its deco color."
#define PT_ELEM_BIZRG_DESC L"Bizarre gas."
#define PT_ELEM_BIZRS_DESC L"Bizarre solid."
#define PT_ELEM_BMTL_DESC L"Breakable metal. Common conductive building material, can melt and break under pressure."
#define PT_ELEM_BOMB_DESC L"Bomb. Explodes and destroys all surrounding particles when it touches something."
#define PT_ELEM_BOYL_DESC L"Boyle, variable pressure gas. Expands when heated."
#define PT_ELEM_BRAY_DESC L"Ray Point. Rays create points when they collide."
#define PT_ELEM_BRCK_DESC L"Brick, breakable building material."
#define PT_ELEM_BREC_DESC L"Broken electronics. Formed from EMP blasts, and when constantly sparked while under pressure, turns to EXOT."
#define PT_ELEM_BRMT_DESC L"Broken metal. Created when iron rusts or when when metals break from pressure."
#define PT_ELEM_BTRY_DESC L"Generates infinite electricity."
#define PT_ELEM_BVBR_DESC L"Broken vibranium."
#define PT_ELEM_C5_DESC L"Cold explosive, set off by anything cold."
#define PT_ELEM_CAUS_DESC L"Caustic Gas, acts like ACID."
#define PT_ELEM_CBNW_DESC L"Carbonated water. Slowly releases CO2."
#define PT_ELEM_CFLM_DESC L"Sub-zero flame."
#define PT_ELEM_CLNE_DESC L"Solid. Duplicates any particles it touches."
#define PT_ELEM_CLST_DESC L"Clay dust. Produces paste when mixed with water."
#define PT_ELEM_CNCT_DESC L"Concrete, stronger than stone."
#define PT_ELEM_CO2_DESC L"Carbon Dioxide. Heavy gas, drifts downwards. Carbonates water and turns to dry ice when cold."
#define PT_ELEM_COAL_DESC L"Coal, Burns very slowly. Gets red when hot."
#define PT_ELEM_CONV_DESC L"Solid. Converts everything into whatever it first touches."
#define PT_ELEM_CRAY_DESC L"Particle Ray Emitter. Creates a beam of particles set by its ctype, with a range set by tmp."
#define PT_ELEM_CRMC_DESC L"Ceramic. Gets stronger under pressure."
#define PT_ELEM_DCEL_DESC L"Decelerator, slows down nearby elements."
#define PT_ELEM_DESL_DESC L"Liquid diesel. Explodes under high pressure and temperatures."
#define PT_ELEM_DEST_DESC L"More destructive Bomb, can break through virtually anything."
#define PT_ELEM_DEUT_DESC L"Deuterium oxide. Volume changes with temp, radioactive with neutrons."
#define PT_ELEM_DLAY_DESC L"Conducts with temperature-dependent delay. (use HEAT/COOL)."
#define PT_ELEM_DMG_DESC L"Generates damaging pressure and breaks any elements it hits."
#define PT_ELEM_DMND_DESC L"Diamond. Indestructible."
#define PT_ELEM_DRAY_DESC L"Duplicator ray. Replicates a line of particles in front of it."
#define PT_ELEM_DRIC_DESC L"Dry Ice, formed when CO2 is cooled."
#define PT_ELEM_DSTW_DESC L"Distilled water, does not conduct electricity."
#define PT_ELEM_DTEC_DESC L"Detector, creates a spark when something with its ctype is nearby."
#define PT_ELEM_DUST_DESC L"Very light dust. Flammable."
#define PT_ELEM_DYST_DESC L"Dead Yeast."
#define PT_ELEM_ELEC_DESC L"Electrons. Sparks electronics, reacts with NEUT and WATR."
#define PT_ELEM_EMBR_DESC L"Sparks. Formed by explosions."
#define PT_ELEM_EMP_DESC L"Electromagnetic pulse. Breaks activated electronics."
#define PT_ELEM_ETRD_DESC L"Electrode. Creates a surface that allows Plasma arcs. (Use sparingly)"
#define PT_ELEM_EXOT_DESC L"Exotic matter. Explodes with excess exposure to electrons. Has many other odd reactions."
#define PT_ELEM_FIGH_DESC L"Fighter. Tries to kill stickmen. You must first give it an element to kill him with."
#define PT_ELEM_FILT_DESC L"Filter for photons, changes the color."
#define PT_ELEM_FIRE_DESC L"Ignites flammable materials. Heats air."
#define PT_ELEM_FIRW_DESC L"Fireworks! Colorful, set off by fire."
#define PT_ELEM_FOG_DESC L"Fog, created when an electric current is passed through RIME."
#define PT_ELEM_FRAY_DESC L"Force Emitter. Pushes or pulls objects based on its temperature. Use like ARAY."
#define PT_ELEM_FRME_DESC L"Frame, can be used with pistons to push many particles."
#define PT_ELEM_FRZW_DESC L"Freeze water. Hybrid liquid formed when Freeze powder melts."
#define PT_ELEM_FRZZ_DESC L"Freeze powder. When melted, forms ice that always cools. Spreads with regular water."
#define PT_ELEM_FSEP_DESC L"Fuse Powder. Burns slowly like FUSE."
#define PT_ELEM_FUSE_DESC L"Burns slowly. Ignites at somewhat high temperatures or with electricity."
#define PT_ELEM_FWRK_DESC L"Original version of fireworks, activated by heat/neutrons."
#define PT_ELEM_GAS_DESC L"Diffuses quickly and flammable. Liquefies into OIL under pressure."
#define PT_ELEM_GBMB_DESC L"Gravity bomb. Sticks to the first object it touches then produces a strong gravity push."
#define PT_ELEM_GEL_DESC L"Gel. A liquid with variable viscosity and heat conductivity."
#define PT_ELEM_GLAS_DESC L"Glass. Meltable. Shatters under pressure, and refracts photons."
#define PT_ELEM_GLOW_DESC L"Glow, Glows under pressure."
#define PT_ELEM_GOLD_DESC L"Corrosion resistant metal, will reverse corrosion of iron."
#define PT_ELEM_GOO_DESC L"Deforms and disappears under pressure."
#define PT_ELEM_GPMP_DESC L"Gravity pump. Changes gravity to its temp when activated. (use HEAT/COOL)"
#define PT_ELEM_GRAV_DESC L"Very light dust. Changes colour based on velocity."
#define PT_ELEM_GRVT_DESC L"Gravitons. Create Newtonian Gravity."
#define PT_ELEM_GUNP_DESC L"Gunpowder. Light dust, explodes on contact with fire or spark."
#define PT_ELEM_H2_DESC L"Hydrogen. Combusts with OXYG to make WATR. Undergoes fusion at high temperature and pressure."
#define PT_ELEM_HSWC_DESC L"Heat switch. Conducts heat only when activated."
#define PT_ELEM_ICEI_DESC L"Crushes under pressure. Cools down air."
#define PT_ELEM_IGNT_DESC L"Ignition cord. Burns slowly with fire and sparks."
#define PT_ELEM_INSL_DESC L"Insulator, does not conduct heat and blocks electricity."
#define PT_ELEM_INST_DESC L"Instantly conducts, PSCN to charge, NSCN to take."
#define PT_ELEM_INVIS_DESC L"Invisible to particles while under pressure."
#define PT_ELEM_INWR_DESC L"Insulated Wire. Doesn't conduct to metal or semiconductors."
#define PT_ELEM_IRON_DESC L"Rusts with salt, can be used for electrolysis of WATR."
#define PT_ELEM_ISOZ_DESC L"Isotope-Z. Radioactive liquid, decays into photons when touching PHOT or under negative pressure."
#define PT_ELEM_ISZS_DESC L"Solid form of ISOZ, slowly decays into PHOT."
#define PT_ELEM_LAVA_DESC L"Molten lava. Ignites flammable materials. Generated when metals and other materials melt, solidifies when cold."
#define PT_ELEM_LCRY_DESC L"Liquid Crystal. Changes colour when charged. (PSCN Charges, NSCN Discharges)"
#define PT_ELEM_LIFE_DESC L"Game Of Life! B3/S23"
#define PT_ELEM_LIGH_DESC L"Lightning. Change the brush size to set the size of the lightning."
#define PT_ELEM_LNTG_DESC L"Liquid Nitrogen. Very cold, disappears whenever it touches anything warmer."
#define PT_ELEM_LO2_DESC L"Liquid Oxygen. Very cold. Reacts with fire."
#define PT_ELEM_LOLZ_DESC L"Lolz"
#define PT_ELEM_LOVE_DESC L"Love..."
#define PT_ELEM_LRBD_DESC L"Liquid Rubidium."
#define PT_ELEM_MERC_DESC L"Mercury. Volume changes with temperature, Conductive."
#define PT_ELEM_METL_DESC L"The basic conductor. Meltable."
#define PT_ELEM_MORT_DESC L"Steam Train."
#define PT_ELEM_MWAX_DESC L"Liquid Wax. Hardens into WAX at 45 degrees."
#define PT_ELEM_NBHL_DESC L"Black hole, sucks in particles using gravity. (Requires Newtonian gravity)"
#define PT_ELEM_NBLE_DESC L"Noble Gas. Diffuses and conductive. Ionizes into plasma when introduced to electricity."
#define PT_ELEM_NEUT_DESC L"Neutrons. Interact with matter in odd ways."
#define PT_ELEM_NICE_DESC L"Nitrogen Ice. Very cold, will melt into LN2 when heated only slightly."
#define PT_ELEM_NITR_DESC L"Nitroglycerin. Pressure sensitive explosive. Mix with CLST to make TNT."
#define PT_ELEM_NONE_DESC L"Erases particles."
#define PT_ELEM_NSCN_DESC L"N-Type Silicon, Will not transfer current to P-Type Silicon."
#define PT_ELEM_NTCT_DESC L"Semi-conductor. Only conducts electricity when hot. (More than 100C)"
#define PT_ELEM_NWHL_DESC L"White hole, pushes away other particles with gravity. (Requires Newtonian gravity)"
#define PT_ELEM_O2_DESC L"Oxygen gas. Ignites easily."
#define PT_ELEM_OIL_DESC L"Flammable, turns into GAS at low pressure or high temperature. Can be formed with NEUT and NITR."
#define PT_ELEM_PBCN_DESC L"Powered breakable clone."
#define PT_ELEM_PCLN_DESC L"Powered clone. When activated, duplicates any particles it touches."
#define PT_ELEM_PHOT_DESC L"Photons. Refracts through glass, scattered by quartz, and color-changed by different elements. Ignites flammable materials."
#define PT_ELEM_PIPE_DESC L"PIPE, moves particles around. Once the BRCK generates, erase some for the exit. Then the PIPE generates and is usable."
#define PT_ELEM_PLEX_DESC L"Solid pressure sensitive explosive."
#define PT_ELEM_PLNT_DESC L"Plant, drinks water and grows."
#define PT_ELEM_PLSM_DESC L"Plasma, extremely hot."
#define PT_ELEM_PLUT_DESC L"Heavy particles. Fissile. Generates neutrons under pressure."
#define PT_ELEM_PPIP_DESC L"Powered version of PIPE, use PSCN/NSCN to Activate/Deactivate."
#define PT_ELEM_PQRT_DESC L"Powdered quartz, broken form of QRTZ."
#define PT_ELEM_PROT_DESC L"Protons. Transfer heat to materials, and removes sparks."
#define PT_ELEM_PRTI_DESC L"Portal IN. Particles go in here. Also has temperature dependent channels. (same as WIFI)"
#define PT_ELEM_PRTO_DESC L"Portal OUT. Particles come out here. Also has temperature dependent channels. (same as WIFI)"
#define PT_ELEM_PSCN_DESC L"P-Type Silicon, Will transfer current to any conductor."
#define PT_ELEM_PSNS_DESC L"Pressure sensor, creates a spark when the pressure is greater than its temperature."
#define PT_ELEM_PSTE_DESC L"Colloid, Hardens under pressure."
#define PT_ELEM_PSTN_DESC L"Piston, extends and pushes particles."
#define PT_ELEM_PSTS_DESC L"Solid form of PSTE."
#define PT_ELEM_PTCT_DESC L"Semi-conductor. Only conducts electricity when cold. (Less than 100C)"
#define PT_ELEM_PUMP_DESC L"Pressure pump. Changes pressure to its temp when activated. (use HEAT/COOL)."
#define PT_ELEM_PVOD_DESC L"Powered VOID. When activated, destroys entering particles."
#define PT_ELEM_QRTZ_DESC L"Quartz, breakable mineral. Conducts but becomes brittle at lower temperatures."
#define PT_ELEM_RBDM_DESC L"Rubidium. Explosive, especially on contact with water. Low melting point."
#define PT_ELEM_RIME_DESC L"Solid, created when steam cools rapidly and goes through sublimation."
#define PT_ELEM_RPEL_DESC L"Repels or attracts particles based on its temperature."
#define PT_ELEM_SALT_DESC L"Salt, dissolves in water."
#define PT_ELEM_SAND_DESC L"Sand, Heavy particles. Melts into glass."
#define PT_ELEM_SHLD1_DESC L"Shield, spark it to grow."
#define PT_ELEM_SHLD2_DESC L"Shield lvl 2."
#define PT_ELEM_SHLD3_DESC L"Shield lvl 3."
#define PT_ELEM_SHLD4_DESC L"Shield lvl 4."
#define PT_ELEM_SING_DESC L"Singularity. Creates huge amounts of negative pressure and destroys everything."
#define PT_ELEM_SLTW_DESC L"Saltwater, conducts electricity, difficult to freeze."
#define PT_ELEM_SMKE_DESC L"Smoke, created by fire."
#define PT_ELEM_SNOW_DESC L"Light particles. Created when ICE breaks under pressure."
#define PT_ELEM_SOAP_DESC L"Soap. Creates bubbles, washes off deco color, and cures virus."
#define PT_ELEM_SPAWN_DESC L"STKM spawn point."
#define PT_ELEM_SPAWN2_DESC L"STK2 spawn point."
#define PT_ELEM_SPNG_DESC L"Sponge, absorbs water. Is not a moving solid."
#define PT_ELEM_SPRK_DESC L"Electricity. The basis of all electronics in TPT, travels along wires and other conductive elements."
#define PT_ELEM_STKM_DESC L"Stickman. Don't kill him! Control with the arrow keys."
#define PT_ELEM_STKM2_DESC L"Second stickman. Don't kill him! Control with wasd."
#define PT_ELEM_STNE_DESC L"Heavy particles. Meltable."
#define PT_ELEM_STOR_DESC L"Captures and stores a single particle. releases when charged with PSCN, also passes to PIPE."
#define PT_ELEM_SWCH_DESC L"Only conducts when switched on. (PSCN switches on, NSCN switches off)"
#define PT_ELEM_TESC_DESC L"Tesla coil! Creates lightning when sparked."
#define PT_ELEM_THDR_DESC L"Lightning! Very hot, inflicts damage upon most materials, and transfers current to metals."
#define PT_ELEM_THRM_DESC L"Thermite. Burns at extremely high temperature."
#define PT_ELEM_TRON_DESC L"Smart particles, Travels in straight lines and avoids obstacles. Grows with time."
#define PT_ELEM_TSNS_DESC L"Temperature sensor, creates a spark when there's a nearby particle with a greater temperature."
#define PT_ELEM_TTAN_DESC L"Titanium. Higher melting temperature than most other metals, blocks all air pressure."
#define PT_ELEM_TUNG_DESC L"Tungsten. Brittle metal with a very high melting point."
#define PT_ELEM_URAN_DESC L"Heavy particles. Generates heat under pressure."
#define PT_ELEM_VIBR_DESC L"Vibranium. Stores energy and releases it in violent explosions."
#define PT_ELEM_VINE_DESC L"Vine, can grow along WOOD."
#define PT_ELEM_VIRS_DESC L"Virus. Turns everything it touches into virus."
#define PT_ELEM_VOID_DESC L"Hole, will drain away any particles."
#define PT_ELEM_VRSG_DESC L"Gas Virus. Turns everything it touches into virus."
#define PT_ELEM_VRSS_DESC L"Solid Virus. Turns everything it touches into virus."
#define PT_ELEM_WARP_DESC L"Displaces other elements."
#define PT_ELEM_WATR_DESC L"Conducts electricity, freezes, and extinguishes fires."
#define PT_ELEM_WAX_DESC L"Wax. Melts at moderately high temperatures."
#define PT_ELEM_WHOL_DESC L"Air vent, creates pressure and pushes other particles away."
#define PT_ELEM_WIFI_DESC L"Wireless transmitter, transfers spark to any other wifi on the same temperature channel."
#define PT_ELEM_WIRE_DESC L"WireWorld wires, conducts based on a set of GOL-like rules."
#define PT_ELEM_WOOD_DESC L"Wood, flammable."
#define PT_ELEM_WTRV_DESC L"Steam. Produced from hot water."
#define PT_ELEM_YEST_DESC L"Yeast, grows when warm (~37C)."
