#define KEY_UP SDLK_UP
#define KEY_DOWN SDLK_DOWN
#define KEY_RIGHT SDLK_RIGHT
#define KEY_LEFT SDLK_LEFT
#define KEY_HOME SDLK_HOME
#define KEY_END SDLK_END
#define KEY_BACKSPACE SDLK_BACKSPACE
#define	KEY_DELETE SDLK_DELETE
#define KEY_TAB SDLK_TAB

#define KEY_MOD_CONTROL KMOD_CTRL
#define KEY_MOD_ALT KMOD_ALT
#define KEY_MOD_SHIFT KMOD_SHIFT

