#define KEY_UP SDLK_UP
#define KEY_DOWN SDLK_DOWN
#define KEY_RIGHT SDLK_RIGHT
#define KEY_LEFT SDLK_LEFT
#define KEY_HOME SDLK_HOME
#define KEY_END SDLK_END
#define KEY_BACKSPACE SDLK_BACKSPACE
#define	KEY_DELETE SDLK_DELETE
#define KEY_TAB SDLK_TAB
#define KEY_RETURN SDLK_RETURN
#define KEY_ENTER SDLK_KP_ENTER

#define KEY_CTRL SDLK_LCTRL
#define KEY_ALT SDLK_LALT
#define KEY_SHIFT SDLK_LSHIFT

#define KEY_MOD_CONTROL KMOD_CTRL
#define KEY_MOD_ALT KMOD_ALT
#define KEY_MOD_SHIFT KMOD_SHIFT

#define BUTTON_LEFT SDL_BUTTON_LEFT
#define BUTTON_MIDDLE SDL_BUTTON_MIDDLE
#define BUTTON_RIGHT SDL_BUTTON_RIGHT
