TRAPDEF(-1, sin)
TRAPDEF(-2, cos)
TRAPDEF(-3, atan2)
TRAPDEF(-4, sqrt)
TRAPDEF(-5, floor)
TRAPDEF(-6, ceil)

TRAPDEF(-7, error)
TRAPDEF(-8, print)
TRAPDEF(-9, partCreate)
TRAPDEF(-10, partChangeType)
TRAPDEF(-11, pmapData)
TRAPDEF(-12, deletePart)
TRAPDEF(-13, killPart)
