################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/elements/O2.cpp \
../src/elements/acel.cpp \
../src/elements/acid.cpp \
../src/elements/amtr.cpp \
../src/elements/anar.cpp \
../src/elements/aray.cpp \
../src/elements/bang.cpp \
../src/elements/bcln.cpp \
../src/elements/bcol.cpp \
../src/elements/bizr.cpp \
../src/elements/bmtl.cpp \
../src/elements/bomb.cpp \
../src/elements/boyl.cpp \
../src/elements/brmt.cpp \
../src/elements/btry.cpp \
../src/elements/c5.cpp \
../src/elements/caus.cpp \
../src/elements/cbnw.cpp \
../src/elements/clne.cpp \
../src/elements/clst.cpp \
../src/elements/co2.cpp \
../src/elements/coal.cpp \
../src/elements/conv.cpp \
../src/elements/dest.cpp \
../src/elements/deut.cpp \
../src/elements/dlay.cpp \
../src/elements/dstw.cpp \
../src/elements/elec.cpp \
../src/elements/elementmisc.cpp \
../src/elements/emp.cpp \
../src/elements/figh.cpp \
../src/elements/fire.cpp \
../src/elements/firw.cpp \
../src/elements/fog.cpp \
../src/elements/fray.cpp \
../src/elements/frzw.cpp \
../src/elements/frzz.cpp \
../src/elements/fsep.cpp \
../src/elements/fuse.cpp \
../src/elements/fwrk.cpp \
../src/elements/gbmb.cpp \
../src/elements/gel.cpp \
../src/elements/glas.cpp \
../src/elements/glow.cpp \
../src/elements/goo.cpp \
../src/elements/gpmp.cpp \
../src/elements/graphics_default.cpp \
../src/elements/h2.cpp \
../src/elements/hswc.cpp \
../src/elements/ice.cpp \
../src/elements/ignt.cpp \
../src/elements/iron.cpp \
../src/elements/isz.cpp \
../src/elements/lava.cpp \
../src/elements/lcry.cpp \
../src/elements/legacy.cpp \
../src/elements/ligh.cpp \
../src/elements/merc.cpp \
../src/elements/mort.cpp \
../src/elements/nbhl.cpp \
../src/elements/nble.cpp \
../src/elements/neut.cpp \
../src/elements/newgraphics.cpp \
../src/elements/none.cpp \
../src/elements/nptct.cpp \
../src/elements/nwhl.cpp \
../src/elements/pbcn.cpp \
../src/elements/pcln.cpp \
../src/elements/phot.cpp \
../src/elements/pipe.cpp \
../src/elements/plnt.cpp \
../src/elements/plsm.cpp \
../src/elements/plut.cpp \
../src/elements/prti.cpp \
../src/elements/prto.cpp \
../src/elements/pump.cpp \
../src/elements/pvod.cpp \
../src/elements/pyro.cpp \
../src/elements/qrtz.cpp \
../src/elements/repl.cpp \
../src/elements/rime.cpp \
../src/elements/shld.cpp \
../src/elements/sing.cpp \
../src/elements/sltw.cpp \
../src/elements/smke.cpp \
../src/elements/soap.cpp \
../src/elements/spng.cpp \
../src/elements/sprk.cpp \
../src/elements/stkm.cpp \
../src/elements/stkm2.cpp \
../src/elements/stor.cpp \
../src/elements/swch.cpp \
../src/elements/thdr.cpp \
../src/elements/thrm.cpp \
../src/elements/tron.cpp \
../src/elements/uran.cpp \
../src/elements/vine.cpp \
../src/elements/warp.cpp \
../src/elements/watr.cpp \
../src/elements/wifi.cpp \
../src/elements/wire.cpp \
../src/elements/wtrv.cpp \
../src/elements/yest.cpp 

OBJS += \
./src/elements/O2.o \
./src/elements/acel.o \
./src/elements/acid.o \
./src/elements/amtr.o \
./src/elements/anar.o \
./src/elements/aray.o \
./src/elements/bang.o \
./src/elements/bcln.o \
./src/elements/bcol.o \
./src/elements/bizr.o \
./src/elements/bmtl.o \
./src/elements/bomb.o \
./src/elements/boyl.o \
./src/elements/brmt.o \
./src/elements/btry.o \
./src/elements/c5.o \
./src/elements/caus.o \
./src/elements/cbnw.o \
./src/elements/clne.o \
./src/elements/clst.o \
./src/elements/co2.o \
./src/elements/coal.o \
./src/elements/conv.o \
./src/elements/dest.o \
./src/elements/deut.o \
./src/elements/dlay.o \
./src/elements/dstw.o \
./src/elements/elec.o \
./src/elements/elementmisc.o \
./src/elements/emp.o \
./src/elements/figh.o \
./src/elements/fire.o \
./src/elements/firw.o \
./src/elements/fog.o \
./src/elements/fray.o \
./src/elements/frzw.o \
./src/elements/frzz.o \
./src/elements/fsep.o \
./src/elements/fuse.o \
./src/elements/fwrk.o \
./src/elements/gbmb.o \
./src/elements/gel.o \
./src/elements/glas.o \
./src/elements/glow.o \
./src/elements/goo.o \
./src/elements/gpmp.o \
./src/elements/graphics_default.o \
./src/elements/h2.o \
./src/elements/hswc.o \
./src/elements/ice.o \
./src/elements/ignt.o \
./src/elements/iron.o \
./src/elements/isz.o \
./src/elements/lava.o \
./src/elements/lcry.o \
./src/elements/legacy.o \
./src/elements/ligh.o \
./src/elements/merc.o \
./src/elements/mort.o \
./src/elements/nbhl.o \
./src/elements/nble.o \
./src/elements/neut.o \
./src/elements/newgraphics.o \
./src/elements/none.o \
./src/elements/nptct.o \
./src/elements/nwhl.o \
./src/elements/pbcn.o \
./src/elements/pcln.o \
./src/elements/phot.o \
./src/elements/pipe.o \
./src/elements/plnt.o \
./src/elements/plsm.o \
./src/elements/plut.o \
./src/elements/prti.o \
./src/elements/prto.o \
./src/elements/pump.o \
./src/elements/pvod.o \
./src/elements/pyro.o \
./src/elements/qrtz.o \
./src/elements/repl.o \
./src/elements/rime.o \
./src/elements/shld.o \
./src/elements/sing.o \
./src/elements/sltw.o \
./src/elements/smke.o \
./src/elements/soap.o \
./src/elements/spng.o \
./src/elements/sprk.o \
./src/elements/stkm.o \
./src/elements/stkm2.o \
./src/elements/stor.o \
./src/elements/swch.o \
./src/elements/thdr.o \
./src/elements/thrm.o \
./src/elements/tron.o \
./src/elements/uran.o \
./src/elements/vine.o \
./src/elements/warp.o \
./src/elements/watr.o \
./src/elements/wifi.o \
./src/elements/wire.o \
./src/elements/wtrv.o \
./src/elements/yest.o 

CPP_DEPS += \
./src/elements/O2.d \
./src/elements/acel.d \
./src/elements/acid.d \
./src/elements/amtr.d \
./src/elements/anar.d \
./src/elements/aray.d \
./src/elements/bang.d \
./src/elements/bcln.d \
./src/elements/bcol.d \
./src/elements/bizr.d \
./src/elements/bmtl.d \
./src/elements/bomb.d \
./src/elements/boyl.d \
./src/elements/brmt.d \
./src/elements/btry.d \
./src/elements/c5.d \
./src/elements/caus.d \
./src/elements/cbnw.d \
./src/elements/clne.d \
./src/elements/clst.d \
./src/elements/co2.d \
./src/elements/coal.d \
./src/elements/conv.d \
./src/elements/dest.d \
./src/elements/deut.d \
./src/elements/dlay.d \
./src/elements/dstw.d \
./src/elements/elec.d \
./src/elements/elementmisc.d \
./src/elements/emp.d \
./src/elements/figh.d \
./src/elements/fire.d \
./src/elements/firw.d \
./src/elements/fog.d \
./src/elements/fray.d \
./src/elements/frzw.d \
./src/elements/frzz.d \
./src/elements/fsep.d \
./src/elements/fuse.d \
./src/elements/fwrk.d \
./src/elements/gbmb.d \
./src/elements/gel.d \
./src/elements/glas.d \
./src/elements/glow.d \
./src/elements/goo.d \
./src/elements/gpmp.d \
./src/elements/graphics_default.d \
./src/elements/h2.d \
./src/elements/hswc.d \
./src/elements/ice.d \
./src/elements/ignt.d \
./src/elements/iron.d \
./src/elements/isz.d \
./src/elements/lava.d \
./src/elements/lcry.d \
./src/elements/legacy.d \
./src/elements/ligh.d \
./src/elements/merc.d \
./src/elements/mort.d \
./src/elements/nbhl.d \
./src/elements/nble.d \
./src/elements/neut.d \
./src/elements/newgraphics.d \
./src/elements/none.d \
./src/elements/nptct.d \
./src/elements/nwhl.d \
./src/elements/pbcn.d \
./src/elements/pcln.d \
./src/elements/phot.d \
./src/elements/pipe.d \
./src/elements/plnt.d \
./src/elements/plsm.d \
./src/elements/plut.d \
./src/elements/prti.d \
./src/elements/prto.d \
./src/elements/pump.d \
./src/elements/pvod.d \
./src/elements/pyro.d \
./src/elements/qrtz.d \
./src/elements/repl.d \
./src/elements/rime.d \
./src/elements/shld.d \
./src/elements/sing.d \
./src/elements/sltw.d \
./src/elements/smke.d \
./src/elements/soap.d \
./src/elements/spng.d \
./src/elements/sprk.d \
./src/elements/stkm.d \
./src/elements/stkm2.d \
./src/elements/stor.d \
./src/elements/swch.d \
./src/elements/thdr.d \
./src/elements/thrm.d \
./src/elements/tron.d \
./src/elements/uran.d \
./src/elements/vine.d \
./src/elements/warp.d \
./src/elements/watr.d \
./src/elements/wifi.d \
./src/elements/wire.d \
./src/elements/wtrv.d \
./src/elements/yest.d 


# Each subdirectory must supply rules for building sources it contributes
src/elements/%.o: ../src/elements/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


